version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest || true
r
  build: # Add the missing build job declaration
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: Build project
          command: echo "Building project..."

workflows:
  sample:
    jobs:
      - build-and-test
      - build: # Add the build job to the workflow
          filters:
            branches:
              only:
                - main
          context: pr-check
       
