version: 2.1



jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
        name: pull files from other repos
        command: git clone https://github.com/shahid962/myorbs.git
        
workflows:
  jobs:
    - build-and-test